### ISSUE TITLE
Add virtual environment segment

### ISSUE THREAD

**Issue by sumanthratna** [Xeoeen/powerline-rust#14]
It'd be great if `powerline-rust` could indicate when Python virtual environments have been activated. It should look something like the screenshot here: https://github.com/justjanne/powerline-go/pull/175 (but of course, only show the name once).

**Comment by cirho** [comment]
If you want it added create pull request. I know it's only few lines of code, but unfortunately I don't have enough time to add every possible module people would want to have.
