### ISSUE TITLE
Support RGB color

### ISSUE THREAD

**Issue by VulpineAmethyst** [Xeoeen/powerline-rust#20]
I would like to see powerline-rust support [24-bit colour](https://en.wikipedia.org/wiki/ANSI_escape_code#24-bit), terminal-side support for which is available in popular terminals such as Konsole, xterm, iTerm2, and alacritty.

**Comment by cirho** [comment]
Sorry for the delay, support of 24-bit color is not planned, because it would only increase complexity of code and similar results can be achieved by mapping 8-bit color into 24-bit color in a terminal config.

**Comment by cirho** [comment]
alacritty: https://github.com/alacritty/alacritty/blob/cf35a2019162c6055e4a4c152976a424ba10869d/alacritty.yml#L311
kitty: https://sw.kovidgoyal.net/kitty/conf/#the-color-table
