### ISSUE TITLE
Use `libgit2` instead of parsing the `git` command

### ISSUE THREAD

**Issue by ArniDagur** [Xeoeen/powerline-rust#7]
This is what [jD91mZM2/powerline-rs](https://github.com/jD91mZM2/powerline-rs) does to increase performance. The [`git2`](https://docs.rs/git2/0.7.5/git2/) crate can be used.

**Comment by cirho** [comment]
I will look into it.

**Comment by cirho** [comment]
I have done some testing and from the results it seems that using git2 is never better than current solution and much often worse. With git2 code looks much cleaner and I would really like to get rid off parsing command output, but not for performance.

If you give me some benchmarks proving your statement I will consider rewriting. 

For testing I simply pasted code from D91mZM2/powerline-rs and modified it to work with my codebase. I can provide you with git2 branch, but tomorrow.

**Comment by ArniDagur** [comment]
Powerline-rs's README.md said that it increases performance; it made sense so I just took their word for it. I haven't done any  benchmarks myself.
